spring:
  profiles:
    active:
      - dev
---
spring:
  config:
    activate:
      on-profile:
        - dev
  kafka:
    topic: library-event
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
